### ISSUE TITLE
result feature doesn't seem to generate correct HUGR for classical programs

### ISSUE THREAD

**Issue by qartik** [CQCL/guppylang#365]
Result function introduced in CQCL/guppylang#271 generates correct HUGR for quantum measurements, such as, `result(0, measure(q))`, but not for a program like the following:

```py
mod = GuppyModule("main")
mod.load(quantum)
@guppy(mod)
def main() -> None:
    a = 1 + 2  # noqa: F841
    result(0, a)
```

**Comment by mark-koch** [comment]
I think this is because the `result` function introduced in #271 doesn't yet conform to the new results extension spec from https://github.com/CQCL/tket2/pull/494. See issue #369

For now, you should be able to make validation pass by not including the`tket2_hseries::extension::result` extension in the registry.

**Comment by mark-koch** [comment]
guppylang v0.9.0 with the fix is released 👍
